# Generated by Django 4.1.3 on 2022-11-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertSystem', '0002_alter_question_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
