# Generated by Django 4.1.3 on 2022-11-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertSystem', '0003_alter_option_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
